### ISSUE TITLE
Recommendation:  how to start ollama without making automatically start on boot

### ISSUE THREAD

**Issue by MikeB2019x** [varunvasudeva1/ollama-server-docs#2]
I installed ollama manually on a remote server.  At the CLI when I tried to run ollama I got the error: `could not connect to ollama app`.  The solution to this is to know that you have to start the ollama server.  That can be done by first running `ollama serve` in a terminal and then use the `ollama run <model>` from another terminal ([mentioned here](https://github.com/ollama/ollama/issues/2727)).  I think this should be added somewhere in the docs.

**Comment by varunvasudeva1** [comment]
Hey @MikeB2019x, I believe this is mentioned in point 3 of the essential steps ('Install `ollama`'), where the environment needs to be configured to listen on 0.0.0.0. The following lines reload `systemd`'s config files and restart the `ollama` service:
```
systemctl daemon-reload
systemctl restart ollama
```

Did you run into the `could not connect to ollama app` error after specifically following these steps?

**Comment by MikeB2019x** [comment]
Hi @varunvasudeva1, tnx for the quick response!  In my case I am installing on an isolated VM/server that I can ssh in to but not much else (VM has very very restricted internet).  So I couldn't use `curl` and the install script but I could download the `ollama` file on another machine and use a manual install (ie. - `scp` the file to the server and then move to /usr/bin).

But once I have the file on the server, it isn't something I need/want started every time the server restarts.  Since, point 3 is only recommended  I guessed it isn't _necessary_ and that there must be another way to just start/stop the server.  It's an edge case maybe but good to know for someone not yet very familiar with ollama.

**Comment by varunvasudeva1** [comment]
Mm, I see where you're coming from. It definitely is an edge case, but I think it's a valuable note to add for people with restricted systems going the manual installation route - I've added it as a tip under the 'Install `ollama`' step and elaborated on it in a point in the Troubleshooting section.

Incidentally, your issue helped me update something closely related to that point: according to the thread you shared, when using `ollama` as a service, running `ollama serve` becomes redundant and, thus, doesn't need to be present in the `init.bash` script.

Appreciate your input greatly, thanks!
